[package]
name = "axum-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = {version = "0.6.1", features = ["headers"] }
serde = { version = "1.0.147", features = ["derive"] }
axum-macros = "0.3.0"
